### ISSUE TITLE
Backup European characters are not supported

### ISSUE THREAD

**Issue by botheis** [medulla-tech/medulla#202]
<a href="https://github.com/tekmans"><img src="https://avatars1.githubusercontent.com/u/1766087?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [tekmans](https://github.com/tekmans)**
_Tuesday Jan 31, 2017 at 16:01 GMT_
_Originally opened as https://github.com/pulse-project/pulse/issues/93_

----

When configuring backup pc within Folder or Exclusion character as exemple : "é" or "è" are not supported.

Traceback :

2017-01-31 15:15:43,194 #140384693569280 ERROR Error during render backuppc.set_host_config: Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 196, in _worker
    result = context.call(ctx, function, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "/usr/lib/pymodules/python2.7/mmc/agent.py", line 252, in _putResult
    result = f(*args, **kwargs)
  File "plugins/backuppc/__init__.py", line 106, in set_host_config
    return bpc.set_host_config(host,config)
  File "/usr/lib/pymodules/python2.7/mmc/plugins/backuppc/bpc.py", line 544, in set_host_config
    html = send_request(params,backupserver)
  File "/usr/lib/pymodules/python2.7/mmc/plugins/backuppc/bpc.py", line 89, in send_request
    params_str = dictToURL(params)
  File "/usr/lib/pymodules/python2.7/mmc/plugins/backuppc/bpc.py", line 74, in dictToURL
    return urllib.urlencode(params)+s
  File "/usr/lib/python2.7/urllib.py", line 1338, in urlencode
    v = quote_plus(str(v))
exceptions.UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 2: ordinal not in range(128)

**Comment by neoclust** [comment]
closing as we are switching to urbackup
